### ISSUE TITLE
POST /login route not exists in the route:list

### ISSUE THREAD

**Issue by geraldarcega** [esbenp/larapi#16]
I cannot submit a POST request on the LoginController which handles the LoginProxy because it does not exists in the route:list

This is the return of my `php artisan route:list`
`
|        | GET|HEAD | oauth/personal-access-tokens            |      | \Laravel\Passport\Http\Controllers\PersonalAccessTokenController@forUser   | web,auth   |
|        | POST     | oauth/personal-access-tokens            |      | \Laravel\Passport\Http\Controllers\PersonalAccessTokenController@store     | web,auth   |
|        | DELETE   | oauth/personal-access-tokens/{token_id} |      | \Laravel\Passport\Http\Controllers\PersonalAccessTokenController@destroy   | web,auth   |
|        | GET|HEAD | oauth/scopes                            |      | \Laravel\Passport\Http\Controllers\ScopeController@all                     | web,auth   |
|        | POST     | oauth/token                             |      | \Laravel\Passport\Http\Controllers\AccessTokenController@issueToken        | throttle   |
|        | POST     | oauth/token/refresh                     |      | \Laravel\Passport\Http\Controllers\TransientTokenController@refresh        | web,auth   |
|        | GET|HEAD | oauth/tokens                            |      | \Laravel\Passport\Http\Controllers\AuthorizedAccessTokenController@forUser | web,auth   |
|        | DELETE   | oauth/tokens/{token_id}                 |      | \Laravel\Passport\Http\Controllers\AuthorizedAccessTokenController@destroy | web,auth   |
`

**Comment by gruz** [comment]
As far as I can see it's there
Check https://github.com/esbenp/larapi/blob/master/infrastructure/Auth/routes_public.php#L3

Here is a screenshot of my case (I have one or a couple of my own routes added for tests)

<a href="http://static.xscreenshot.com/2017/05/04/17/screen_d3120f5ff3c197b7d9b1082b7b990c48" rel="group[xscreenshot]"  class="jcepopup" data-mediabox-height="600" data-mediabox-group="xscreenshot" data-mediabox-width="800"><img width="300" src="http://static.xscreenshot.com/2017/05/04/17/screen_d3120f5ff3c197b7d9b1082b7b990c48"></a>

**Comment by shaklev** [comment]
@geraldarcega  You are probably missing `Infrastructure\Http\RouteServiceProvider::class`  in the `providers` arrray ( inside   `config/app.php`

**Comment by esbenp** [comment]
Closed due to inactivity.
