### ISSUE TITLE
For correct work under Windows

### ISSUE THREAD

**Issue by StudiowebPro** [esbenp/larapi#17]
Remove base_path() from config i think not good idea. 
I think, that good idea change file 

Optimus/distributed-laravel/RouteServiceProvider.php

replace line 72
`$component = substr($componentRoot, strrpos($componentRoot, '/') + 1);`
to:
`$component = substr($componentRoot, strrpos($componentRoot, DIRECTORY_SEPARATOR) + 1);`

esbenp, please fix it in package -)

**Comment by esbenp** [comment]
Fixed https://github.com/esbenp/distributed-laravel/commit/086525c48e61ff7ce47e2627a7629e4b734ba630
