### ISSUE TITLE
CORs issuse

### ISSUE THREAD

**Issue by tomibolo** [esbenp/larapi#21]
Hi, 

I built up this APi but when i tried to connect via a React App (with browser) im having some troubles:

XMLHttpRequest cannot load http://localhost:8000/login. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

It looks that there is a COR problem, but i have no idea how can i fix it up using your app.

Where should i change headers in order to add Access-Control-Allow-Origin?

Thanks!!

**Comment by z2z** [comment]
Check if this works for you ... 
Enable https://github.com/esbenp/larapi/search?utf8=%E2%9C%93&q=cors&type=
and use https://github.com/asm89/stack-cors

or 
https://medium.com/@mshanak/solved-laravel-5-3-passport-with-cors-2c6667ef058b

**Comment by tomibolo** [comment]
Thank you z2z, worked like a charm. Only had to install Barryvdh\Cors\ServiceProvider::class. 
Best regards!!!!
