### ISSUE TITLE
Wrong auth

### ISSUE THREAD

**Issue by mrminh231189** [esbenp/larapi#24]
Option 1: Login success -> ok not problem
Option 2: Login unsuccess -> "exception 'Infrastructure\\Auth\\Exceptions\\InvalidCredentialsException' ... "

Can help me, plz ?

**Comment by esbenp** [comment]
Yes, please update Laravel passport to `^3.0`. You can see the changes here https://github.com/esbenp/larapi/commit/c0d4e626f9a6055e1f543ce6acecb29a25bdeda0
