### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by egbertmza** [esbenp/larapi#25]
HI,

I am using your laravel implementation for my API and trying to see how i can implement GraphQL into it. Any advise ?

struggling a bit with the how/where to set it up considering your structure different to a default Laravel structure.

Thx

**Comment by esbenp** [comment]
I am unsure as I am not well versed in GraphQL. But maybe [this can give you a starting point](https://github.com/Folkloreatelier/laravel-graphql)
