### ISSUE TITLE
Question: How a SPA should be handling token refresh

### ISSUE THREAD

**Issue by jbaron-mx** [esbenp/larapi#4]
I just read the [lastest blog post](http://esbenp.github.io/2017/03/19/modern-rest-api-laravel-part-4/) (awesome tutorial btw) and as far as I understand, it needs an extra request to refresh the token, this leave me questions regarding the implementation on a SPA:

Is the SPA job to track the token expiracy in order to request a refreshed one before any other resource request takes place?

Refreshing the token within the same resource request would not be better?

**Comment by esbenp** [comment]
Hey. I have made a small library that achieves this in redux (react.js). https://github.com/esbenp/redux-refresh-token

I think I will write a blog post about it soon. You can sign up for my newsletter on my blog and you will get a notification about it.

**Comment by jbaron-mx** [comment]
It's actually pretty clear the approach you take by viewing that library. Thanks, I'll keep an eye on your next posts.
