### ISSUE TITLE
what's the point on having a proxy ?

### ISSUE THREAD

**Issue by anandsiddharth** [esbenp/larapi#47]
what's the point on having a proxy, one's the proxy url is exposed any one can use the link to create access tokens with same app id and secret since it's handled inside proxy..

**Comment by alexcomo95** [comment]
Anyone has an answer?

I thought the same thing. From what I understand, it is an information-hiding mechanism for the client's credentials. But in other words, if an attacker has the URL, the proxy will authenticate them. So it's the same as having the credentials in the first place. It's nice to see that the client does not need to know about sensitive client credentials. But nobody does!

I hope it wasn't a mistake and there is a reason for that.

**Comment by esbenp** [comment]
I am not sure I understand your concerns, but I think I wrote about it here http://esbenp.github.io/2017/03/19/modern-rest-api-laravel-part-4/

It's a while ago so its not up-to-date

**Comment by alexcomo95** [comment]
Not up to date, but still useful in my opinion.

I read the whole thing and from what I understand, the proxy's purpose is to hide the client's credentials. But then, the client doesn't need to authenticate itself with the API. The proxy will do it. But the proxy is not verifying the source of the requests it receives. So anyone can pass requests and be authenticated just by knowing the proxy's URL.

Maybe I just missed the point. That's what I'm wondering.

**Comment by nlbailey** [comment]
I'm new to using Laravel/Passport in general and as I was reading through the article I had the same question as well. Any requests made to the API will have the client id/secret added with the proxy making any request have the authorized client id/secret. But if they are embedded in the client, yes there is a good chance they will be discovered but at least not every request is authorized. Am I missing something?
