### ISSUE TITLE
controller not exist.

### ISSUE THREAD

**Issue by ntc113** [esbenp/larapi#5]
i was installed success but run get errors:
- access: http://locahost:8000
==> {"status":"error","code":-1,"message":"Class Infrastructure\\:....larapi-master\\infrastructure\\Api\\Controllers\\DefaultApiController does not exist"
- access: http://locahost:8000/users
==> {"status":"error","code":-1,"message":"Class Api\\:......\\larapi-master\\api\\Users\\Controllers\\UserController does not exist"

DefaultApiController.php and UserController.php has exist on the my sourcecode.
thanks

**Comment by ntc113** [comment]
i added full path in route and resolved this issue.
$router->get('/', '\Infrastructure\Api\Controllers\DefaultApiController@index');
instead of
$router->get('/', 'DefaultApiController@index');

**Comment by od3n** [comment]
@ntc113 are you on windows? i'm getting same error on windows, but no problem on mac

**Comment by pbarrientosc** [comment]
i was installed success but run get errors:
access: 
http://locahost:8000/users
==> {"status":"error","code":-1,"message":"Class Api\:......\larapi-master\api\Users\Controllers\UserController does not exist"
I work in windows.

**Comment by pbarrientosc** [comment]
I solved this problem:
**Before**:
$router->get('/users', 'UserController@getAll');
**After**:
$router->get('/users', '\Api\Users\Controllers\UserController@getAll');

**Comment by ntc113** [comment]
@od3n im use windows, i added fullpath and success.
