### ISSUE TITLE
How do I create a user using laravel passport?

### ISSUE THREAD

**Issue by arifkhn46** [esbenp/larapi#6]
I clone the larapi repo and installed the dependencies successfully then I made following request using curl:

curl -X POST -H 'Content-Type: application/json' -d '{"user": {"email": "user@user.com", "name": "A user", "password": "12345678"}}'  http://apis.mydomain.dev/users

server returns following response:

<pre>{
   "status":"error",
   "code":0,
   "message":"Unauthenticated.",
   "exception":"Illuminate\\Auth\\AuthenticationException: Unauthenticated. ......."
   "line":66,
   "file":"project/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php"
}</pre>

**Comment by od3n** [comment]
@ak-incaendo you missed this step

`php artisan users:add Esben esben@esben.dk 1234
`

**Comment by KgotsoK** [comment]
How about user registration from the client

**Comment by esbenp** [comment]
You need to create public routes in your User component.

```
/Users
   /Controllers
   / ...etc
   /Services
   /routes.php
   /routes_public.php <--- does not require authentication
```

In `routes_public.php`

```
<?php

$router->post('/register', 'UserController@register');
```

And then you just create a registration method and so forth. Then from your client (example with jquery or similar):
```
$.post('/register', {
  email: 'esben@esben.dk',
  password: '1234'
});
```
